on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  get-data:
    runs-on: ubuntu-latest
    name: Get Data
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run "action.yml"
        uses: ./
      - name: Commit and push
        run: |
          git diff
          git add .
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated data.json" -a
          git push